# Generated by Django 5.2.5 on 2025-08-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_employee_phone_number_employee_phone_and_more"),
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance",
                to="employees.employee",
            ),
        ),
    ]
