# Generated by Django 5.2.5 on 2025-08-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
