# Generated by Django 5.2.5 on 2025-08-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_rename_phone_employee_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(default="0000000000", max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="employees.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
